Course.find_or_create_by(name: 'Ciência da computação', shift: 'morning')
Course.find_or_create_by(name: 'Engenharia', shift: 'evening')
Course.find_or_create_by(name: 'Medicina', shift: 'evening')
Course.find_or_create_by(name: 'Biologia', shift: 'evening')
Course.find_or_create_by(name: 'Educação Física', shift: 'integral')
