AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'
    - !ruby/regexp /old_and_unused\.rb$/

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/Lambda:
  Enabled: false