Category.find_or_create_by(name: 'Comidas', image: 'categories/comidas.jpg')
Category.find_or_create_by(name: 'Vestimentas', image: 'categories/vestimentas.jpg')
Category.find_or_create_by(name: 'Livros', image: 'categories/livros.jpeg')
Category.find_or_create_by(name: 'Moradias', image: 'categories/moradias.jpeg')
Category.find_or_create_by(name: 'Serviços', image: 'categories/servicos.jpg')
Category.find_or_create_by(name: 'Artes', image: 'categories/artes.jpg')
Category.find_or_create_by(name: 'Outros', image: 'categories/outros.png')
