Course.find_or_create_by(name: '* Não é estudante', shift: 'integral')
Course.find_or_create_by(name: 'Administração', shift: 'morning')
Course.find_or_create_by(name: 'Administração', shift: 'nocturnal')
Course.find_or_create_by(name: 'Agronomia', shift: 'integral')
Course.find_or_create_by(name: 'Biomedicina', shift: 'integral')
Course.find_or_create_by(name: 'Ciência da computação', shift: 'integral')
Course.find_or_create_by(name: 'Ciências biológicas', shift: 'integral')
Course.find_or_create_by(name: 'Ciências biológicas', shift: 'nocturnal')
Course.find_or_create_by(name: 'Ciências contábeis', shift: 'nocturnal')
Course.find_or_create_by(name: 'Ciências sociais', shift: 'nocturnal')
Course.find_or_create_by(name: 'Comunicação social', shift: 'evening')
Course.find_or_create_by(name: 'Direito', shift: 'integral')
Course.find_or_create_by(name: 'Direito', shift: 'nocturnal')
Course.find_or_create_by(name: 'Economia', shift: 'morning')
Course.find_or_create_by(name: 'Economia', shift: 'integral')
Course.find_or_create_by(name: 'Educação física', shift: 'integral')
Course.find_or_create_by(name: 'Enfermagem', shift: 'integral')
Course.find_or_create_by(name: 'Engenharia civil', shift: 'integral')
Course.find_or_create_by(name: 'Engenharia de produção', shift: 'integral')
Course.find_or_create_by(name: 'Engenharia elétrica', shift: 'integral')
Course.find_or_create_by(name: 'Engenharia mecânica', shift: 'integral')
Course.find_or_create_by(name: 'Engenharia química', shift: 'integral')
Course.find_or_create_by(name: 'Filosofia', shift: 'nocturnal')
Course.find_or_create_by(name: 'Filosofia', shift: 'evening')
Course.find_or_create_by(name: 'Física', shift: 'integral')
Course.find_or_create_by(name: 'Física', shift: 'nocturnal')
Course.find_or_create_by(name: 'Geografia', shift: 'integral')
Course.find_or_create_by(name: 'Geografia', shift: 'nocturnal')
Course.find_or_create_by(name: 'História', shift: 'morning')
Course.find_or_create_by(name: 'História', shift: 'nocturnal')
Course.find_or_create_by(name: 'Letras', shift: 'morning')
Course.find_or_create_by(name: 'Letras', shift: 'nocturnal')
Course.find_or_create_by(name: 'Línguas estrangeiras', shift: 'evening')
Course.find_or_create_by(name: 'Matemática', shift: 'integral')
Course.find_or_create_by(name: 'Matemática', shift: 'nocturnal')
Course.find_or_create_by(name: 'Medicina', shift: 'integral')
Course.find_or_create_by(name: 'Medicina veterinária', shift: 'integral')
Course.find_or_create_by(name: 'Pedagogia', shift: 'morning')
Course.find_or_create_by(name: 'Pedagogia', shift: 'nocturnal')
Course.find_or_create_by(name: 'Química', shift: 'integral')
